plugins {
    id 'com.android.library' version '8.12.1'
}

repositories {
    google()
    mavenCentral()
    // This will force trying to resolve from the old repository
    maven { url "https://google.bintray.com/exoplayer" }
}

dependencies {
    // No explicit dependencies needed for test build
}

android {
    compileSdkVersion 35
    namespace 'test.package'
}